##################################################################################
#
# Laravel API Response Builder CodeCov.io config file
#
# @package   Taxionus\ResponseBuilder
#
# @author    Ahamed Riham <mail (#) riham.dev (.) com>
# @copyright 2016-2022 Ahamed Riham
# @license   http://www.opensource.org/licenses/mit-license.php MIT
# @link      https://github.com/MarcinOrlowski/laravel-api-response-builder
#
##################################################################################

comment: false
